version: "3"
services:
  db:
    image: postgres:12
    container_name: auth-api
    environment:
      POSTGRES_USER: danillo
      POSTGRES_PASSWORD: danillo
      POSTGRES_DB: auth-api
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
    driver: local